package com.naga.yulian.entity;

import java.util.Date;

public class Accounting {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.uuid
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.topId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private String topid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.userId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.createrId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private String createrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.createDate
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.type
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.currency
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private Integer currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.currencyBefore
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private Integer currencybefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.point
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private Integer point;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accounting.pointBefore
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    private Integer pointbefore;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.uuid
     *
     * @return the value of accounting.uuid
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.uuid
     *
     * @param uuid the value for accounting.uuid
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.topId
     *
     * @return the value of accounting.topId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public String getTopid() {
        return topid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.topId
     *
     * @param topid the value for accounting.topId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setTopid(String topid) {
        this.topid = topid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.userId
     *
     * @return the value of accounting.userId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.userId
     *
     * @param userid the value for accounting.userId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.createrId
     *
     * @return the value of accounting.createrId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public String getCreaterid() {
        return createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.createrId
     *
     * @param createrid the value for accounting.createrId
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setCreaterid(String createrid) {
        this.createrid = createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.createDate
     *
     * @return the value of accounting.createDate
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.createDate
     *
     * @param createdate the value for accounting.createDate
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.type
     *
     * @return the value of accounting.type
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.type
     *
     * @param type the value for accounting.type
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.currency
     *
     * @return the value of accounting.currency
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public Integer getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.currency
     *
     * @param currency the value for accounting.currency
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setCurrency(Integer currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.currencyBefore
     *
     * @return the value of accounting.currencyBefore
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public Integer getCurrencybefore() {
        return currencybefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.currencyBefore
     *
     * @param currencybefore the value for accounting.currencyBefore
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setCurrencybefore(Integer currencybefore) {
        this.currencybefore = currencybefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.point
     *
     * @return the value of accounting.point
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public Integer getPoint() {
        return point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.point
     *
     * @param point the value for accounting.point
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setPoint(Integer point) {
        this.point = point;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accounting.pointBefore
     *
     * @return the value of accounting.pointBefore
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public Integer getPointbefore() {
        return pointbefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accounting.pointBefore
     *
     * @param pointbefore the value for accounting.pointBefore
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    public void setPointbefore(Integer pointbefore) {
        this.pointbefore = pointbefore;
    }
}