package com.naga.yulian.entity;

import java.util.Date;

public class Accusation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.uuid
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.topId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private String topid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.userId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.createrId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private String createrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.createDate
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.type
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accusation.remarks
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.uuid
     *
     * @return the value of accusation.uuid
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.uuid
     *
     * @param uuid the value for accusation.uuid
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.topId
     *
     * @return the value of accusation.topId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public String getTopid() {
        return topid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.topId
     *
     * @param topid the value for accusation.topId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setTopid(String topid) {
        this.topid = topid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.userId
     *
     * @return the value of accusation.userId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.userId
     *
     * @param userid the value for accusation.userId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.createrId
     *
     * @return the value of accusation.createrId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public String getCreaterid() {
        return createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.createrId
     *
     * @param createrid the value for accusation.createrId
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setCreaterid(String createrid) {
        this.createrid = createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.createDate
     *
     * @return the value of accusation.createDate
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.createDate
     *
     * @param createdate the value for accusation.createDate
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.type
     *
     * @return the value of accusation.type
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.type
     *
     * @param type the value for accusation.type
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accusation.remarks
     *
     * @return the value of accusation.remarks
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accusation.remarks
     *
     * @param remarks the value for accusation.remarks
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }
}