package com.naga.yulian.entity;

import java.util.Date;

public class Advise {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advise.uuid
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advise.remarks
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advise.createrId
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    private String createrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advise.createDate
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advise.uuid
     *
     * @return the value of advise.uuid
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advise.uuid
     *
     * @param uuid the value for advise.uuid
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advise.remarks
     *
     * @return the value of advise.remarks
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advise.remarks
     *
     * @param remarks the value for advise.remarks
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advise.createrId
     *
     * @return the value of advise.createrId
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public String getCreaterid() {
        return createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advise.createrId
     *
     * @param createrid the value for advise.createrId
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public void setCreaterid(String createrid) {
        this.createrid = createrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advise.createDate
     *
     * @return the value of advise.createDate
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advise.createDate
     *
     * @param createdate the value for advise.createDate
     *
     * @mbggenerated Mon May 16 14:28:38 CST 2016
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}