package com.naga.yulian.entity;

public class Levelname {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column levelname.uuid
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column levelname.start
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    private Integer start;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column levelname.end
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    private Integer end;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column levelname.levelName
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    private String levelname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column levelname.uuid
     *
     * @return the value of levelname.uuid
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column levelname.uuid
     *
     * @param uuid the value for levelname.uuid
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column levelname.start
     *
     * @return the value of levelname.start
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public Integer getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column levelname.start
     *
     * @param start the value for levelname.start
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public void setStart(Integer start) {
        this.start = start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column levelname.end
     *
     * @return the value of levelname.end
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public Integer getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column levelname.end
     *
     * @param end the value for levelname.end
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public void setEnd(Integer end) {
        this.end = end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column levelname.levelName
     *
     * @return the value of levelname.levelName
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public String getLevelname() {
        return levelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column levelname.levelName
     *
     * @param levelname the value for levelname.levelName
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    public void setLevelname(String levelname) {
        this.levelname = levelname;
    }
}