package com.naga.yulian.entity;

public class Mobilevalidate {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mobilevalidate.mobile
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mobilevalidate.validateId
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	private String validateid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mobilevalidate.mobile
	 * @return  the value of mobilevalidate.mobile
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mobilevalidate.mobile
	 * @param mobile  the value for mobilevalidate.mobile
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mobilevalidate.validateId
	 * @return  the value of mobilevalidate.validateId
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	public String getValidateid() {
		return validateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mobilevalidate.validateId
	 * @param validateid  the value for mobilevalidate.validateId
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	public void setValidateid(String validateid) {
		this.validateid = validateid;
	}
}