package com.naga.yulian.entity;

import java.math.BigDecimal;
import java.util.Date;

public class User {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.uuid
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String uuid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.userId
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String userid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.passWrod
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String passwrod;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.name
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.birthday
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private Date birthday;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.sex
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private Short sex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.job
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String job;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.clas
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private Short clas;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.point
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String point;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.currency
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private BigDecimal currency;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.gps
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.remark
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String remark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.updaterId
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String updaterid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.updateDate
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private Date updatedate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.status
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private Short status;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.vx
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String vx;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.qq
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String qq;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column user.face
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	private String face;

	// 经度
	private String latitude;
	// 纬度
	private String longitude;

	public String getLatitude() {
		return latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	public String getLongitude() {
		return longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.uuid
	 *
	 * @return the value of user.uuid
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getUuid() {
		return uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.uuid
	 *
	 * @param uuid
	 *            the value for user.uuid
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setUuid(String uuid) {
		this.uuid = uuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.userId
	 *
	 * @return the value of user.userId
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.userId
	 *
	 * @param userid
	 *            the value for user.userId
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setUserid(String userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.passWrod
	 *
	 * @return the value of user.passWrod
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getPasswrod() {
		return passwrod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.passWrod
	 *
	 * @param passwrod
	 *            the value for user.passWrod
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setPasswrod(String passwrod) {
		this.passwrod = passwrod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.name
	 *
	 * @return the value of user.name
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.name
	 *
	 * @param name
	 *            the value for user.name
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.birthday
	 *
	 * @return the value of user.birthday
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public Date getBirthday() {
		return birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.birthday
	 *
	 * @param birthday
	 *            the value for user.birthday
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.sex
	 *
	 * @return the value of user.sex
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public Short getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.sex
	 *
	 * @param sex
	 *            the value for user.sex
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setSex(Short sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.job
	 *
	 * @return the value of user.job
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getJob() {
		return job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.job
	 *
	 * @param job
	 *            the value for user.job
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setJob(String job) {
		this.job = job;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.clas
	 *
	 * @return the value of user.clas
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public Short getClas() {
		return clas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.clas
	 *
	 * @param clas
	 *            the value for user.clas
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setClas(Short clas) {
		this.clas = clas;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.point
	 *
	 * @return the value of user.point
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getPoint() {
		return point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.point
	 *
	 * @param point
	 *            the value for user.point
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setPoint(String point) {
		this.point = point;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.currency
	 *
	 * @return the value of user.currency
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public BigDecimal getCurrency() {
		return currency;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.currency
	 *
	 * @param currency
	 *            the value for user.currency
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setCurrency(BigDecimal currency) {
		this.currency = currency;
	}




	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.remark
	 *
	 * @return the value of user.remark
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.remark
	 *
	 * @param remark
	 *            the value for user.remark
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.updaterId
	 *
	 * @return the value of user.updaterId
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getUpdaterid() {
		return updaterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.updaterId
	 *
	 * @param updaterid
	 *            the value for user.updaterId
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setUpdaterid(String updaterid) {
		this.updaterid = updaterid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.updateDate
	 *
	 * @return the value of user.updateDate
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public Date getUpdatedate() {
		return updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.updateDate
	 *
	 * @param updatedate
	 *            the value for user.updateDate
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.status
	 *
	 * @return the value of user.status
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.status
	 *
	 * @param status
	 *            the value for user.status
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.vx
	 *
	 * @return the value of user.vx
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getVx() {
		return vx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.vx
	 *
	 * @param vx
	 *            the value for user.vx
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setVx(String vx) {
		this.vx = vx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.qq
	 *
	 * @return the value of user.qq
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getQq() {
		return qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.qq
	 *
	 * @param qq
	 *            the value for user.qq
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setQq(String qq) {
		this.qq = qq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column user.face
	 *
	 * @return the value of user.face
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public String getFace() {
		return face;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column user.face
	 *
	 * @param face
	 *            the value for user.face
	 *
	 * @mbggenerated Tue May 10 14:26:45 CST 2016
	 */
	public void setFace(String face) {
		this.face = face;
	}

	public void setCurrency(int i) {
		// TODO Auto-generated method stub
		
	}
}