package com.naga.yulian.entity;

import java.util.Date;

public class Version {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.uuid
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private String uuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.versionNo
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private String versionno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.remarks
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.forced
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private Integer forced;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.system
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private Integer system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.path
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private String path;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column version.updateDate
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    private Date updatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.uuid
     *
     * @return the value of version.uuid
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.uuid
     *
     * @param uuid the value for version.uuid
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.versionNo
     *
     * @return the value of version.versionNo
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public String getVersionno() {
        return versionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.versionNo
     *
     * @param versionno the value for version.versionNo
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setVersionno(String versionno) {
        this.versionno = versionno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.remarks
     *
     * @return the value of version.remarks
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.remarks
     *
     * @param remarks the value for version.remarks
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.forced
     *
     * @return the value of version.forced
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public Integer getForced() {
        return forced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.forced
     *
     * @param forced the value for version.forced
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setForced(Integer forced) {
        this.forced = forced;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.system
     *
     * @return the value of version.system
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public Integer getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.system
     *
     * @param system the value for version.system
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setSystem(Integer system) {
        this.system = system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.path
     *
     * @return the value of version.path
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.path
     *
     * @param path the value for version.path
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column version.updateDate
     *
     * @return the value of version.updateDate
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column version.updateDate
     *
     * @param updatedate the value for version.updateDate
     *
     * @mbggenerated Mon May 16 10:51:17 CST 2016
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }
}