package com.naga.common.entity;

public class UpldFileMng {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.oId
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String oId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.upldFileNm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String upldFileNm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.genFileNm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String genFileNm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.delFlg
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String delFlg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.updtUsr
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String updtUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.updtTm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String updtTm;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.crtdUsr
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String crtdUsr;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column t_upld_file_mng.crtdTm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    private String crtdTm;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.oId
     * @return  the value of t_upld_file_mng.oId
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getoId() {
        return oId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.oId
     * @param oId  the value for t_upld_file_mng.oId
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setoId(String oId) {
        this.oId = oId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.upldFileNm
     * @return  the value of t_upld_file_mng.upldFileNm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getUpldFileNm() {
        return upldFileNm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.upldFileNm
     * @param upldFileNm  the value for t_upld_file_mng.upldFileNm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setUpldFileNm(String upldFileNm) {
        this.upldFileNm = upldFileNm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.genFileNm
     * @return  the value of t_upld_file_mng.genFileNm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getGenFileNm() {
        return genFileNm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.genFileNm
     * @param genFileNm  the value for t_upld_file_mng.genFileNm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setGenFileNm(String genFileNm) {
        this.genFileNm = genFileNm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.delFlg
     * @return  the value of t_upld_file_mng.delFlg
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getDelFlg() {
        return delFlg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.delFlg
     * @param delFlg  the value for t_upld_file_mng.delFlg
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setDelFlg(String delFlg) {
        this.delFlg = delFlg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.updtUsr
     * @return  the value of t_upld_file_mng.updtUsr
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getUpdtUsr() {
        return updtUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.updtUsr
     * @param updtUsr  the value for t_upld_file_mng.updtUsr
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setUpdtUsr(String updtUsr) {
        this.updtUsr = updtUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.updtTm
     * @return  the value of t_upld_file_mng.updtTm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getUpdtTm() {
        return updtTm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.updtTm
     * @param updtTm  the value for t_upld_file_mng.updtTm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setUpdtTm(String updtTm) {
        this.updtTm = updtTm;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.crtdUsr
     * @return  the value of t_upld_file_mng.crtdUsr
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getCrtdUsr() {
        return crtdUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.crtdUsr
     * @param crtdUsr  the value for t_upld_file_mng.crtdUsr
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setCrtdUsr(String crtdUsr) {
        this.crtdUsr = crtdUsr;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column t_upld_file_mng.crtdTm
     * @return  the value of t_upld_file_mng.crtdTm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public String getCrtdTm() {
        return crtdTm;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column t_upld_file_mng.crtdTm
     * @param crtdTm  the value for t_upld_file_mng.crtdTm
     * @mbggenerated  Wed Apr 27 18:30:45 CST 2016
     */
    public void setCrtdTm(String crtdTm) {
        this.crtdTm = crtdTm;
    }
}