package com.naga.yulian.dao;

import com.naga.yulian.entity.Accounting;

public interface AccountingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    int insert(Accounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    int insertSelective(Accounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    Accounting selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    int updateByPrimaryKeySelective(Accounting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accounting
     *
     * @mbggenerated Mon May 16 17:07:43 CST 2016
     */
    int updateByPrimaryKey(Accounting record);
}