package com.naga.yulian.dao;

import com.naga.yulian.entity.Accusation;

public interface AccusationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accusation
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accusation
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    int insert(Accusation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accusation
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    int insertSelective(Accusation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accusation
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    Accusation selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accusation
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    int updateByPrimaryKeySelective(Accusation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accusation
     *
     * @mbggenerated Tue May 17 11:23:10 CST 2016
     */
    int updateByPrimaryKey(Accusation record);
}