package com.naga.yulian.dao;

import com.naga.yulian.entity.Levelname;

public interface LevelnameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table levelname
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table levelname
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    int insert(Levelname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table levelname
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    int insertSelective(Levelname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table levelname
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    Levelname selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table levelname
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    int updateByPrimaryKeySelective(Levelname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table levelname
     *
     * @mbggenerated Fri May 20 14:21:46 CST 2016
     */
    int updateByPrimaryKey(Levelname record);
}