package com.naga.yulian.dao;

import com.naga.yulian.entity.Mobilevalidate;

public interface MobilevalidateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mobilevalidate
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	int deleteByPrimaryKey(String mobile);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mobilevalidate
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	int insert(Mobilevalidate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mobilevalidate
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	int insertSelective(Mobilevalidate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mobilevalidate
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	Mobilevalidate selectByPrimaryKey(String mobile);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mobilevalidate
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	int updateByPrimaryKeySelective(Mobilevalidate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mobilevalidate
	 * @mbggenerated  Tue May 17 11:17:59 CST 2016
	 */
	int updateByPrimaryKey(Mobilevalidate record);
}